development:
 adapter: mysql2
 database: the_milky_way_db
 username: <%= ENV['DB_USERNAME'] %>
 password: <%= ENV['DB_PASSWORD'] %>
 host: localhost
 encoding: utf8

test:
 database: testdb
 adapter: mysql2
 encoding: utf8
 username: <%= ENV['DB_USERNAME'] %>
 password: <%= ENV['DB_PASSWORD'] %>
 host: localhost

production:
 adapter: mysql2
 database: Railsdb
 username: <%= ENV['DB_USERNAME'] %>
 password: <%= ENV['DB_PASSWORD'] %>
 host: localhost
 encoding: utf8